name: xiaozhi-flex-alarm-zhangMonday

on:
  schedule:
    - cron: "*/10 * * * *"   # 每 10 分钟运行一次
  push:
    paths:
      - "config/tasks.json"
      - "scripts/**"
  workflow_dispatch:

jobs:
  run-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tasks
        run: node scripts/run.js

